2025-03-01 14:34:20,997 INFO    MainThread:30700 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 14:34:20,997 INFO    MainThread:30700 [wandb_setup.py:_flush():67] Configure stats pid to 30700
2025-03-01 14:34:20,997 INFO    MainThread:30700 [wandb_setup.py:_flush():67] Loading settings from C:\Users\mohak\.config\wandb\settings
2025-03-01 14:34:20,997 INFO    MainThread:30700 [wandb_setup.py:_flush():67] Loading settings from c:\Users\mohak\OneDrive\Documents\GitHub\Distance-based-classification\wandb\settings
2025-03-01 14:34:20,997 INFO    MainThread:30700 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 14:34:20,997 ERROR   MainThread:30700 [wandb_setup.py:_flush():69] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohak\AppData\Local\Temp\ipykernel_30700\3551603027.py", line 13, in <module>
    wandb.init(project='distance_classification_project')
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_init.py", line 1485, in init
    wandb._sentry.reraise(e)
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\analytics\sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_init.py", line 1433, in init
    wi.maybe_login(init_settings)
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_init.py", line 175, in maybe_login
    wandb_login._login(
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_login.py", line 305, in _login
    key, key_status = wlogin.prompt_api_key()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_login.py", line 227, in prompt_api_key
    key, status = self._prompt_api_key()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\wandb_login.py", line 206, in _prompt_api_key
    key = apikey.prompt_api_key(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\wandb\sdk\lib\apikey.py", line 171, in prompt_api_key
    key = input_callback(api_ask).strip()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\mohak\OneDrive\Documents\GitHub\Distance-based-classification\wandb\run-20250301_143420-caq3ndbe\logs\debug.log
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\mohak\OneDrive\Documents\GitHub\Distance-based-classification\wandb\run-20250301_143420-caq3ndbe\logs\debug-internal.log
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002639A14FD50>
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:init():761] calling init triggers
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:init():784] starting backend
2025-03-01 14:34:21,012 INFO    MainThread:30700 [wandb_init.py:init():788] sending inform_init request
2025-03-01 14:34:21,030 INFO    MainThread:30700 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 14:34:21,031 INFO    MainThread:30700 [wandb_init.py:init():803] backend started and connected
2025-03-01 14:34:21,031 INFO    MainThread:30700 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 14:34:21,036 INFO    MainThread:30700 [wandb_init.py:init():896] updated telemetry
2025-03-01 14:34:21,036 INFO    MainThread:30700 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 14:34:22,544 INFO    MainThread:30700 [wandb_init.py:init():995] starting run threads in backend
2025-03-01 14:34:22,642 INFO    MainThread:30700 [wandb_run.py:_console_start():2377] atexit reg
2025-03-01 14:34:22,642 INFO    MainThread:30700 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-01 14:34:22,642 INFO    MainThread:30700 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-01 14:34:22,642 INFO    MainThread:30700 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-01 14:34:22,647 INFO    MainThread:30700 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-01 14:34:22,648 INFO    MainThread:30700 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:34:22,649 INFO    MainThread:30700 [wandb_init.py:_pause_backend():564] pausing backend
